//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DriveBuddyWpfApp.MVVM.Models
{
    using System;
    using System.Collections.ObjectModel;
    
    public partial class Car
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Car()
        {
            this.Lessons = new ObservableCollection<Lesson>();
        }
    
        public int CarID { get; set; }
        public string Mark { get; set; }
        public string Model { get; set; }
        public string RegistrationNumber { get; set; }
        public DateTime ReviewDate { get; set; }
        public int CategoryID { get; set; }
        public string CourseCategory => Category.CategoryName;
        public string ReviewDateText => ReviewDate.ToString("d");
        public string FullName => $"{Mark} {Model}";

        public virtual Category Category { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ObservableCollection<Lesson> Lessons { get; set; }
    }
}
