//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DriveBuddyWpfApp.MVVM.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Lesson
    {
        public int LessonID { get; set; }
        public System.DateTime LessonDate { get; set; }
        public string Title { get; set; }
        public Nullable<byte> HoursNumber { get; set; }
        public int CourseCategoryID { get; set; }
        public int InstructorID { get; set; }
        public int CarID { get; set; }
        public int StudentID { get; set; }
        public string LessonDateText => LessonDate.ToString("d");

        public virtual Car Car { get; set; }
        public virtual Category Category { get; set; }
        public virtual Instructor Instructor { get; set; }
        public virtual Student Student { get; set; }
    }
}
